/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prestamos;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Alexy jr
 */
public class Prestamos extends javax.swing.JFrame {

    /**
     * Creates new form Prestamos
     */
    public Prestamos() {
        initComponents();
        setLocationRelativeTo(this);
        ap.CargarArchivo();

        if (!Personas.isEmpty()) {
            for (int i = 0; i < Personas.size(); i++) {
                int pagos = ((Persona)Personas.get(i)).getMeses();
                int Monto = ((Persona)Personas.get(i)).getMonto();
                for (int j = 0; j < pagos; j++) {
                    ((Persona)Personas.get(i)).getPagos().add(Monto);
                }
            }
        }
        //t_MesMonto.addMouseListener(new TableMouseListener(t_MesMonto));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_AgregarPersonas = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AgregarMeses = new javax.swing.JSpinner();
        AgregarNombre = new javax.swing.JTextField();
        AgregarMonto = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jd_Reportes = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        cb_Clientes = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_MesMonto = new javax.swing.JTable();
        ppm_modificar = new javax.swing.JPopupMenu();
        Pagar = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Nombre Completo");

        jLabel2.setText("Monto del prestamo");

        jLabel3.setText("Meses");

        jButton3.setText("Agregar prestamo");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_AgregarPersonasLayout = new javax.swing.GroupLayout(jd_AgregarPersonas.getContentPane());
        jd_AgregarPersonas.getContentPane().setLayout(jd_AgregarPersonasLayout);
        jd_AgregarPersonasLayout.setHorizontalGroup(
            jd_AgregarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarPersonasLayout.createSequentialGroup()
                .addGroup(jd_AgregarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AgregarPersonasLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jd_AgregarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(25, 25, 25)
                        .addGroup(jd_AgregarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgregarMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgregarMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_AgregarPersonasLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jd_AgregarPersonasLayout.setVerticalGroup(
            jd_AgregarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarPersonasLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jd_AgregarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AgregarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jd_AgregarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AgregarMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jd_AgregarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AgregarMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jd_Reportes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jd_ReportesMouseMoved(evt);
            }
        });

        jLabel4.setText("Clientes");

        cb_Clientes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_ClientesItemStateChanged(evt);
            }
        });

        t_MesMonto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mes", "Monto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t_MesMonto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                t_MesMontoMouseMoved(evt);
            }
        });
        t_MesMonto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_MesMontoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_MesMonto);
        if (t_MesMonto.getColumnModel().getColumnCount() > 0) {
            t_MesMonto.getColumnModel().getColumn(0).setResizable(false);
            t_MesMonto.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jd_ReportesLayout = new javax.swing.GroupLayout(jd_Reportes.getContentPane());
        jd_Reportes.getContentPane().setLayout(jd_ReportesLayout);
        jd_ReportesLayout.setHorizontalGroup(
            jd_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ReportesLayout.createSequentialGroup()
                .addGroup(jd_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ReportesLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_ReportesLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jd_ReportesLayout.setVerticalGroup(
            jd_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ReportesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jd_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        Pagar.setText("Pagar");
        Pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarActionPerformed(evt);
            }
        });
        ppm_modificar.add(Pagar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("AGREGAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("REPORTES");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jd_AgregarPersonas.setModal(true);
        jd_AgregarPersonas.pack();
        jd_AgregarPersonas.setLocationRelativeTo(this);
        jd_AgregarPersonas.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        String Nombre;
        int Monto;
        int TiempoAPagar;

        Nombre = AgregarNombre.getText();
        Monto = Integer.parseInt(AgregarMonto.getText());
        TiempoAPagar = (int) AgregarMeses.getValue();

        if (TiempoAPagar == 1) {
            TiempoAPagar++;
        }

        Persona p = new Persona(Nombre, Monto, TiempoAPagar);
        Personas.add(p);
        cb_Clientes.addItem(p);
        ap.setPersona(p);

        for (int i = 0; i < TiempoAPagar; i++) {
            ((Persona) (Personas.get(Personas.size() - 1))).getPagos().add(Monto);
        }

        AgregarNombre.setText("");
        AgregarMonto.setText("");
        AgregarMeses.setValue(0);

        JOptionPane.showMessageDialog(this, "Has agregado a una persona",
                "OPERACION EXITOSA", JOptionPane.INFORMATION_MESSAGE);

        jd_AgregarPersonas.setVisible(false);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        jd_Reportes.setModal(true);
        jd_Reportes.pack();
        jd_Reportes.setLocationRelativeTo(this);
        jd_Reportes.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void cb_ClientesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_ClientesItemStateChanged
        // TODO add your handling code here:
        DefaultTableModel ModeloTabla = (DefaultTableModel) t_MesMonto.getModel();
        int Filas = ModeloTabla.getRowCount();
        for (int i = 1; i <= Filas; i++) {
            ModeloTabla.removeRow(0);
        }

        Persona temp = (Persona) cb_Clientes.getSelectedItem();

        if (!Personas.isEmpty()) {
            for (int i = 0; i < temp.getPagos().size(); i++) {
                ModeloTabla.addRow(new Object[]{i + 1, temp.getPagos().get(i)});
            }
        }

    }//GEN-LAST:event_cb_ClientesItemStateChanged

    private void t_MesMontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_MesMontoMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            ppm_modificar.show(evt.getComponent(), evt.getX(), evt.getY());
            //t_MesMonto.setComponentPopupMenu(ppm_modificar);
        }
    }//GEN-LAST:event_t_MesMontoMouseClicked

    private void PagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarActionPerformed
        // TODO add your handling code here:
        int PagoEfectuado = 0;
        int MontoAnterior = 0;

        int Fila = t_MesMonto.getSelectedRow();
        String PagoTemp = JOptionPane.showInputDialog("Cantidad a pagar: ");

        PagoEfectuado = Integer.parseInt(PagoTemp);
        MontoAnterior = ((Persona) cb_Clientes.getSelectedItem()).getPagos().get(Fila);

        if (MontoAnterior == PagoEfectuado) {
            ((Persona) cb_Clientes.getSelectedItem()).getPagos().remove(Fila);
        } else if (PagoEfectuado > MontoAnterior) {
            JOptionPane.showMessageDialog(this, "El pago excede el monto",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            ((Persona) cb_Clientes.getSelectedItem()).getPagos().set(Fila, MontoAnterior - PagoEfectuado);
        }
    }//GEN-LAST:event_PagarActionPerformed

    private void jd_ReportesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jd_ReportesMouseMoved
        // TODO add your handling code here:
        DefaultTableModel ModeloTabla = (DefaultTableModel) t_MesMonto.getModel();
        int Filas = ModeloTabla.getRowCount();
        for (int i = 1; i <= Filas; i++) {
            ModeloTabla.removeRow(0);
        }

        Persona temp = (Persona) cb_Clientes.getSelectedItem();

        if (!Personas.isEmpty()) {
            for (int i = 0; i < temp.getPagos().size(); i++) {
                ModeloTabla.addRow(new Object[]{i + 1, temp.getPagos().get(i)});
            }
        }

        for (int i = 0; i < Personas.size(); i++) {
            if ((((Persona) Personas.get(i)).getPagos().isEmpty())) {
                Personas.remove(i);
                cb_Clientes.removeAllItems();
                for (int j = 0; j < Personas.size() - 1; j++) {
                    cb_Clientes.addItem(Personas.get(j));
                }
            }
        }

        ap.EscribirArchivo();
    }//GEN-LAST:event_jd_ReportesMouseMoved

    private void t_MesMontoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_MesMontoMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_t_MesMontoMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner AgregarMeses;
    private javax.swing.JTextField AgregarMonto;
    private javax.swing.JTextField AgregarNombre;
    private javax.swing.JMenuItem Pagar;
    private javax.swing.JComboBox cb_Clientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jd_AgregarPersonas;
    private javax.swing.JDialog jd_Reportes;
    private javax.swing.JPopupMenu ppm_modificar;
    private javax.swing.JTable t_MesMonto;
    // End of variables declaration//GEN-END:variables
ArrayList Personas = new ArrayList();
    Administrar_personas ap = new Administrar_personas("./Clientes.txt");
}
